# Generated by Django 3.2.8 on 2021-11-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211125_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Liker',
            new_name='liker',
        ),
    ]
