# Generated by Django 3.2.8 on 2022-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211212_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
