# Generated by Django 3.2.8 on 2022-06-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_post_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saving_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
