# Generated by Django 3.2.8 on 2022-06-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220615_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photos',
            new_name='photoes',
        ),
    ]
