# Generated by Django 3.2.8 on 2022-06-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='influnced',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='influnced', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='influncer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influncer', to=settings.AUTH_USER_MODEL),
        ),
    ]
