# Generated by Django 3.2.8 on 2022-07-05 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_auto_20220616_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photoes',
            field=models.ManyToManyField(blank=True, related_name='photoes', to='api.Photo'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('photoes', models.ManyToManyField(blank=True, related_name='stories', to='api.Photo')),
            ],
        ),
    ]
